package org.camunda.distributed.integration.commons;

public enum WfPropertyConstants {
    SETTINGS_SERVICE_URL,
    SETTINGS_SERVICE_CONTEXT,
    SETTINGS_TEMP_DOCUMENTS_ROOTPATH,
    SETTINGS_SERVICE_DOCUMENT_DISTRIBUTION_ENDPOINT_URL,
    WFE_ROUTING_KEY,
    UPLOAD_SERVICE_CLEANUP_DELAY
}
